name: CI Pipeline

# Trigger the workflow on push or pull request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3  # Updated to v3, which uses Node.js 16
    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to v4, which uses Node.js 16
      with:
        python-version: 3.11.9

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  deploy:
    if: ${{ github.ref == 'refs/heads/main' && success() }}
    runs-on: windows-latest
    needs: build

    steps:
    - uses: actions/checkout@v3  # Updated to v3, which uses Node.js 16
    
    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to v4, which uses Node.js 16
      with:
        python-version: 3.11.9

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy Application
      run: |
        # Add your deployment script or commands here
        echo "Deployment step - Replace with your deployment process"
